In [1]:
from lightfm import LightFM
from lightfm.cross_validation import random_train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix

/Users/alextsai/anaconda3/lib/python3.7/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '


In [88]:
%%time
listen_data = pd.read_table('data/train_triplets.txt', header = None)
listen_data.columns = ['user_id','item_id','listen_count']

CPU times: user 31.1 s, sys: 6.28 s, total: 37.4 s
Wall time: 38.6 s


In [5]:
small_file = 'https://static.turi.com/datasets/millionsong/10000.txt'
listen_data_small = pd.read_table(small_file, header = None)
listen_data_small.columns = ['user_id','item_id','listen_count']

In [57]:
data_small_pivot = listen_data_small.pivot(index = 'user_id',columns='item_id',values='listen_count')
data_small_pivot = data_small_pivot.fillna(0)
value_matrix = csr_matrix(data_small_pivot)

In [61]:
songs = pd.DataFrame(data_small_pivot.columns)

In [76]:
songs['title'] = [song_data.loc[song_id].title for song_id in songs.item_id]

In [83]:
songs['artist'] = [song_data.loc[song_id].artist_name for song_id in songs.item_id]
songs['year'] = [song_data.loc[song_id].year for song_id in songs.item_id]

In [90]:
listen_data.item_id


0           SOAKIMP12A8C130995
1           SOAPDEY12A81C210A9
2           SOBBMDR12A8C13253B
3           SOBFNSP12AF72A0E22
4           SOBFOVM12A58A7D494
                   ...        
48373581    SOUHHHH12AF729E4AF
48373582    SOUJVIT12A8C1451C1
48373583    SOUSMXX12AB0185C24
48373584    SOWYSKH12AF72A303A
48373585    SOYYFLV12A58A7A88F
Name: item_id, Length: 48373586, dtype: object

In [86]:
pd.read_csv('data/msd_tagtraum_cd1.cls')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 3


In [40]:
value_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
song_data = pd.read_csv('data/song_data (1).csv', index_col=0)
song_data

title  \
song_id                                                   
SOQMMHC12AB0180CB8                         Silent Night   
SOVFVAK12A8C1350D9                          Tanssi vaan   
SOGTUKN12AB017F4F1                    No One Could Ever   
SOBNYVR12A8C13558C                        Si Vos Querés   
SOHSBXH12A8C13B0DF                     Tangle Of Aspens   
...                                                 ...   
SOTXAME12AB018F136                      O Samba Da Vida   
SOXQYIQ12A8C137FBB                         Jago Chhadeo   
SOHODZI12A8C137BB3                              Novemba   
SOLXGOR12A81C21EB7                              Faraday   
SOWXJXQ12AB0189F43  Fernweh feat. Sektion Kuchikäschtli   

                                                 release       artist_name  \
song_id                                                                      
SOQMMHC12AB0180CB8                 Monster Ballads X-Mas  Faster Pussy cat   
SOVFVAK12A8C1350D9                           Karkuteillä  Karkkiautomaatti   
SOGTUKN12AB017F4F1                                Butter    Hudson Mohawke   
SOBNYVR12A8C13558C                               De Culo       Yerba Brava   
SOHSBXH12A8C13B0DF  Rene Ablaze Presents Winter Sessions        Der Mystic   
...                                                  ...               ...   
SOTXAME12AB018F136                          Pacha V.I.P.      Kiko Navarro   
SOXQYIQ12A8C137FBB              Naale Baba Lassi Pee Gya     Kuldeep Manak   
SOHODZI12A8C137BB3       Dub_Connected: electronic music    Gabriel Le Mar   
SOLXGOR12A81C21EB7          The Trance Collection Vol. 2             Elude   
SOWXJXQ12AB0189F43                            So Oder So             Texta   

                    year  
song_id                   
SOQMMHC12AB0180CB8  2003  
SOVFVAK12A8C1350D9  1995  
SOGTUKN12AB017F4F1  2006  
SOBNYVR12A8C13558C  2003  
SOHSBXH12A8C13B0DF     0  
...                  ...  
SOTXAME12AB018F136     0  
SOXQYIQ12A8C137FBB     0  
SOHODZI12A8C137BB3     0  
SOLXGOR12A81C21EB7     0  
SOWXJXQ12AB0189F43  2004  

[1000000 rows x 4 columns]

In [72]:
model_fm = LightFM(loss = 'warp')
model_fm.fit(value_matrix, epochs = 20)

In [50]:
song_df = pd.merge(listen_data_small, song_data.drop_duplicates(), left_on="item_id", right_index=True,how="left")

In [54]:
song_df

user_id             item_id  \
0        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   
...                                           ...                 ...   
1999995  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJEYPO12AAA8C6B0E   
1999996  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJJYDE12AF729FC16   
1999997  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJKQSF12A6D4F5EE9   
1999998  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJUXGA12AC961885C   
1999999  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJYOLS12A8C13C06F   

         listen_count                           title  \
0                   1                        The Cove   
1                   2                 Entre Dos Aguas   
2                   1                        Stronger   
3                   1                  Constellations   
4                   1                    Learn To Fly   
...               ...                             ...   
1999995             2       Ignorance (Album Version)   
1999996             4          Two Is Better Than One   
1999997             3  What I've Done (Album Version)   
1999998             1                              Up   
1999999             1      Soil_ Soil (Album Version)   

                               release  \
0                   Thicker Than Water   
1                  Flamenco Para Niños   
2                           Graduation   
3                    In Between Dreams   
4        There Is Nothing Left To Lose   
...                                ...   
1999995                      Ignorance   
1999996                     Love Drunk   
1999997                 What I've Done   
1999998                      My Worlds   
1999999                        The Con   

                                    artist_name    year  
0                                  Jack Johnson     0.0  
1                                 Paco De Lucia  1976.0  
2                                    Kanye West  2007.0  
3                                  Jack Johnson  2005.0  
4                                  Foo Fighters  1999.0  
...                                         ...     ...  
1999995                                Paramore     0.0  
1999996  Boys Like Girls featuring Taylor Swift  2009.0  
1999997                             Linkin Park  2007.0  
1999998                           Justin Bieber  2010.0  
1999999                          Tegan And Sara  2007.0  

[2049948 rows x 7 columns]

In [55]:
users = song_df['user_id'].unique()


In [32]:
song_grouped = song_df.groupby(['song']).agg({'listen_count': 'count'}).reset_index()
grouped_sum = song_grouped['listen_count'].sum()
song_grouped['percentage']  = song_grouped['listen_count'].div(grouped_sum)*100
song_grouped.sort_values(['listen_count', 'song'], ascending = [0,1])


KeyError: 'song'

In [57]:
len(songs)

10000

In [34]:
song_data

song_id                                title  \
0       SOQMMHC12AB0180CB8                         Silent Night   
1       SOVFVAK12A8C1350D9                          Tanssi vaan   
2       SOGTUKN12AB017F4F1                    No One Could Ever   
3       SOBNYVR12A8C13558C                        Si Vos Querés   
4       SOHSBXH12A8C13B0DF                     Tangle Of Aspens   
...                    ...                                  ...   
999995  SOTXAME12AB018F136                      O Samba Da Vida   
999996  SOXQYIQ12A8C137FBB                         Jago Chhadeo   
999997  SOHODZI12A8C137BB3                              Novemba   
999998  SOLXGOR12A81C21EB7                              Faraday   
999999  SOWXJXQ12AB0189F43  Fernweh feat. Sektion Kuchikäschtli   

                                     release       artist_name  year  
0                      Monster Ballads X-Mas  Faster Pussy cat  2003  
1                                Karkuteillä  Karkkiautomaatti  1995  
2                                     Butter    Hudson Mohawke  2006  
3                                    De Culo       Yerba Brava  2003  
4       Rene Ablaze Presents Winter Sessions        Der Mystic     0  
...                                      ...               ...   ...  
999995                          Pacha V.I.P.      Kiko Navarro     0  
999996              Naale Baba Lassi Pee Gya     Kuldeep Manak     0  
999997       Dub_Connected: electronic music    Gabriel Le Mar     0  
999998          The Trance Collection Vol. 2             Elude     0  
999999                            So Oder So             Texta  2004  

[1000000 rows x 5 columns]

In [81]:
def sample_recommendation(model, user_ids):
    n_users, n_items = value_matrix.shape
    for user_id in user_ids:
        known_positives = songs.iloc[value_matrix[user_id].indices].title
        
        scores = model.predict(user_id, np.arange(n_items))

        top_items = songs.iloc[np.argsort(-scores)].title

        print("User %s" % user_id)
        print("     Known positives:")
        
        for x in known_positives[:3]:
            print("        %s" % x)
        
        print("     Recommended:")
        
        for x in top_items[:3]:
            print("        %s" % x)

In [68]:
value_matrix[0].indices

array([3731, 4125, 5146, 5228, 8366, 8375, 8866], dtype=int32)

In [69]:
songs.iloc[3731]

item_id    SOJJRVI12A6D4FBE49
Name: 3731, dtype: object

In [133]:
score = model_fm.predict(9, np.arange(10000))

In [150]:
score

array([-0.6577996 , -0.33380014, -1.10026658, ..., -1.95935917,
       -2.24011326, -1.65542388])

In [153]:
rank = model_fm.predict_rank(value_matrix)

In [160]:
rank.toarray()[0,1]

0.0

In [135]:
np.argsort(-score)

array([8772, 9678, 2220, ..., 7694, 1136, 5431])

In [136]:
songs[np.argsort(-score)]

array(['SOXAUYB12B0B8078C4', 'SOFWUMY12A6D4FCFB1', 'SOCQSDB12A6D4FA5D2',
       ..., 'SONJNCV12A6D4F95AC', 'SOEOLGZ12A8C134706',
       'SOWWWFF12A6701C7EB'], dtype=object)

In [137]:
np.argsort(-score)

array([8772, 9678, 2220, ..., 7694, 1136, 5431])

In [82]:
sample_recommendation(model_fm, [0,5,90])

User 0
     Known positives:
        Only You (Illuminate Album Version)
        Do You Want To Know Love (Pray For Rain Album Version)
        You're A Wolf (Album)
     Recommended:
        Canada
        Tive Sim
        Dog Days Are Over (Radio Edit)
User 5
     Known positives:
        Nightlite (Zero dB Reconstruction - Radio Edit)
        All In Forms
        Triumphant
     Recommended:
        Paradise Circus
        Atlas Air
        This Old House w/ When The Saints Medley
User 90
     Known positives:
        Hey (Album Version)
        Sin Documentos
        Dog Days Are Over (Radio Edit)
     Recommended:
        The Scientist
        Clocks
        song_id
SOPXKYD12A6D4FA876    Yellow
SOPXKYD12A6D4FA876    Yellow
Name: title, dtype: object


In [71]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
song_df[song_df.song_id == 'SOOPZGS12A8AE4571D']

user_id             item_id  \
14263    e9b86ca8cd62f072419112174f1a9427dd40aed7  SOOPZGS12A8AE4571D   
33872    470c65144c49b122c4be2ea008cba342b7af2a9d  SOOPZGS12A8AE4571D   
36543    34c327464b7c8eaf912e6ba37cadcb64514b5900  SOOPZGS12A8AE4571D   
72793    56761a8994c50ff4269fef0052dc075e1bf2688a  SOOPZGS12A8AE4571D   
96983    4ec767712349220570ac2346c66a2a02c730eb2e  SOOPZGS12A8AE4571D   
...                                           ...                 ...   
1910342  29bce3ce70f3e22e4a8c305314e7400517a96ec8  SOOPZGS12A8AE4571D   
1938292  d71e62620b160d8c83e11d0a2b2cee50cf263892  SOOPZGS12A8AE4571D   
1971935  24b98f8ab023f6e7a1c37c7729c623f7b821eb95  SOOPZGS12A8AE4571D   
1972799  17444da967c6d8b38c59f7ad124fc3925d138a8c  SOOPZGS12A8AE4571D   
1980274  4936c19ee81b586edebbd5cf58bea097d1a342c1  SOOPZGS12A8AE4571D   

         listen_count             song_id                          title  \
14263               2  SOOPZGS12A8AE4571D  Long Division (Album Version)   
33872               1  SOOPZGS12A8AE4571D  Long Division (Album Version)   
36543               2  SOOPZGS12A8AE4571D  Long Division (Album Version)   
72793               1  SOOPZGS12A8AE4571D  Long Division (Album Version)   
96983               3  SOOPZGS12A8AE4571D  Long Division (Album Version)   
...               ...                 ...                            ...   
1910342             3  SOOPZGS12A8AE4571D  Long Division (Album Version)   
1938292             1  SOOPZGS12A8AE4571D  Long Division (Album Version)   
1971935             1  SOOPZGS12A8AE4571D  Long Division (Album Version)   
1972799             1  SOOPZGS12A8AE4571D  Long Division (Album Version)   
1980274             1  SOOPZGS12A8AE4571D  Long Division (Album Version)   

               release          artist_name  year  
14263    Narrow Stairs  Death Cab for Cutie  2008  
33872    Narrow Stairs  Death Cab for Cutie  2008  
36543    Narrow Stairs  Death Cab for Cutie  2008  
72793    Narrow Stairs  Death Cab for Cutie  2008  
96983    Narrow Stairs  Death Cab for Cutie  2008  
...                ...                  ...   ...  
1910342  Narrow Stairs  Death Cab for Cutie  2008  
1938292  Narrow Stairs  Death Cab for Cutie  2008  
1971935  Narrow Stairs  Death Cab for Cutie  2008  
1972799  Narrow Stairs  Death Cab for Cutie  2008  
1980274  Narrow Stairs  Death Cab for Cutie  2008  

[105 rows x 8 columns]

In [118]:
song_df.groupby('song_id').sum().sort_values(by='listen_count', ascending=False)

listen_count      year
song_id                                   
SOBONKR12A58A7A7E0         54136  12759880
SOAUWYT12A81C206F1         49253  14071032
SOSXLTC12AF72A7F54         41418  12339160
SOEGIYH12A6D4FC0E3         31153         0
SOFRQTD12A81C233C0         31036         0
...                          ...       ...
SOAKZQA12A6D4F80C1            76    129610
SOSLEFC12A6D4FC740            75         0
SOENALO12AB01836F5            73    120060
SONQGQE12A670209BC            73    124310
SOJYVPY12A67ADE729            71    130325

[10000 rows x 2 columns]

## TRAIN TEST SPLIT

In [20]:
from lightfm.evaluation import auc_score, precision_at_k, recall_at_k, reciprocal_rank


In [8]:
state = np.random.RandomState(seed = 1)

In [9]:
train, test = random_train_test_split(value_matrix, random_state = state)

In [10]:
model = LightFM(loss = 'warp',random_state = 42)


In [27]:
model.fit(train, epochs = 20)

In [28]:
aucs = auc_score(model, test, train_interactions= train)

In [30]:
aucs.mean()

0.8695011

In [33]:
precs = precision_at_k(model, test ,train_interactions=train, k = 10)

In [35]:
train_prec = precision_at_k(model, train)

In [34]:
precs.mean()

0.041643262

In [36]:
train_prec.mean()

0.12874672

In [32]:
precs

array([0.  , 0.06, 0.02, ..., 0.  , 0.  , 0.08], dtype=float32)

In [11]:
epochs = 70
warp_auc = []
p_k = []
r_k = []
for epoch in range(epochs):
    model.fit_partial(train, epochs=1)
    warp_auc.append(auc_score(model, test, train_interactions=train).mean())
    print(epoch)

KeyboardInterrupt: 

In [ ]:
x = np.arange(epochs)
plt.plot(x, np.array(warp_auc))
plt.legend(['WARP AUC'], loc='upper right')
plt.show()

In [98]:
from scipy.sparse import csr_matrix
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm


class EASE:
    def __init__(self):
        self.user_enc = LabelEncoder()
        self.item_enc = LabelEncoder()

    def _get_users_and_items(self, df):
        users = self.user_enc.fit_transform(df.loc[:, 'user_id'])
        items = self.item_enc.fit_transform(df.loc[:, 'item_id'])
        return users, items

    def fit(self, df, lambda_: float = 0.5, implicit=True):
        """
        df: pandas.DataFrame with columns user_id, item_id and (rating)
        lambda_: l2-regularization term
        implicit: if True, ratings are ignored and taken as 1, else normalized ratings are used
        """
        users, items = self._get_users_and_items(df)
        values = np.ones(df.shape[0]) if implicit else df['rating'].to_numpy() / df['rating'].max()

        X = csr_matrix((values, (users, items)))
        self.X = X

        G = X.T.dot(X).toarray()
        diagIndices = np.diag_indices(G.shape[0])
        G[diagIndices] += lambda_
        P = np.linalg.inv(G)
        B = P / (-np.diag(P))
        B[diagIndices] = 0

        self.B = B
        self.pred = X.dot(B)

    def predict(self, train, users, items, k):
        df = pd.DataFrame()
        items = self.item_enc.transform(items)
        dd = train.loc[train.user_id.isin(users)]
        dd['ci'] = self.item_enc.transform(dd.item_id)
        dd['cu'] = self.user_enc.transform(dd.user_id)
        g = dd.groupby('user_id')
        for user, group in tqdm(g):
            watched = set(group['ci'])
            candidates = [item for item in items if item not in watched]
            u = group['cu'].iloc[0]
            pred = np.take(self.pred[u, :], candidates)
            res = np.argpartition(pred, -k)[-k:]
            r = pd.DataFrame({
                "user_id": [user] * len(res),
                "item_id": np.take(candidates, res),
                "score": np.take(pred, res)
            }).sort_values('score', ascending=False)
            df = df.append(r, ignore_index=True)
        df['item_id'] = self.item_enc.inverse_transform(df['item_id'])
        return df


In [92]:
ease = EASE()

In [93]:
ease.fit(listen_data_small)

In [101]:
ease.predict(listen_data_small,['b80344d063b5ccb3212f76538f3d9e43d87dca9e','d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92'], items = songs.item_id, k=10)

/Users/alextsai/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/alextsai/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:45: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
100%|██████████| 2/2 [00:00<00:00, 189.12it/s]


user_id             item_id     score
0   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOHENSJ12AAF3B2A03  0.442092
1   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMBNVR12AF72A736E  0.394855
2   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SONAZWN12A8151C957  0.361787
3   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOWIMTL12A8C1386DC  0.315567
4   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOHMFHE12AAF3B3E07  0.296127
5   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOYYIZT12A8C1408CA  0.275161
6   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOECLAD12AAF3B120A  0.249974
7   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOCMHGT12A8C138D8A  0.235783
8   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOPNLBX12A8C1377D4  0.223034
9   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOUGHFP12A8C13CD5D  0.222104
10  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOLFXKT12AB017E3E0  0.544183
11  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SONYKOW12AB01849C9  0.517585
12  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOTWNDJ12A8C143984  0.462748
13  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SORWLTW12A670208FA  0.437069
14  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOKLRPJ12A8C13C3FE  0.408384
15  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOXFPND12AB017C9D1  0.362155
16  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOSXLTC12AF72A7F54  0.359179
17  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOISNSU12AC468C0D8  0.351224
18  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOBONKR12A58A7A7E0  0.333917
19  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SONHQJF12A8C1451AB  0.312740

In [97]:
listen_data_small

user_id             item_id  \
0        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   
...                                           ...                 ...   
1999995  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJEYPO12AAA8C6B0E   
1999996  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJJYDE12AF729FC16   
1999997  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJKQSF12A6D4F5EE9   
1999998  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJUXGA12AC961885C   
1999999  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJYOLS12A8C13C06F   

         listen_count  
0                   1  
1                   2  
2                   1  
3                   1  
4                   1  
...               ...  
1999995             2  
1999996             4  
1999997             3  
1999998             1  
1999999             1  

[2000000 rows x 3 columns]